### ISSUE TITLE
[Proposal] Plugin configuration should be passed to plugins

### ISSUE THREAD

**Issue by austinkelleher** [brianleroux/arc-prototype-deploy#3]
# Problem

I need config to be allowed to be passed to plugins. My use case is I have specific paths to marko pages that need to be prebuilt in a plugin:

Example `.arc` config:
```js
...
@plugins
arc-plugin-marko
    pages ./src/html/get-index/page.marko ./src/html/get-page/page.marko
```

# How

Currently, arc passes some configuration to `beforeDeploy` and `afterDeploy` hooks, but does not allow custom plugin configuration specified in `.arc` to be passed. I propose that we attach an additional property to the configuration that is already being passed `pluginConfig`.

-----

I have already implemented the above. I am open to suggestions, but I will open up a PR in the meantime.

**Comment by brianleroux** [comment]
Sweet. Yes I like where this is goin!

Since the whole file gets parsed and passed in we could let plugins define their own sections:

```
@plugins
arc-plugin-marko

@marko
./src/html/get-index/page.marko 
./src/html/get-page/page.marko
```

Maybe a bit cleaner?

**Comment by austinkelleher** [comment]
@brianleroux I think I'd rather the plugins specify the configuration as regular properties. It's unlikely that this would ever happen, but it's technically possible that there would be more than one plugin that would expect the same property and then the parsing would be ambiguous.

For example:

 ```
@plugins
arc-plugin-marko
arc-plugin-markoify

@marko
./src/html/get-index/page.marko 
./src/html/get-page/page.marko

@marko
someproperty
```
