### ISSUE TITLE
[Proposal] Re-install modules conditionally using environment variable

### ISSUE THREAD

**Issue by austinkelleher** [brianleroux/arc-prototype-deploy#7]
## Problem

Currently, when `arc-prototype-deploy` runs, we install modules using `cipm` as one of the tasks. This is perfect when running from a CI, but if you're running from your local machine, you may have modules linked in that you do not want to get overwritten.

## Proposal

We could either inspect `NODE_ENV` or introduce a new environment variable that arc inspects to determine whether the install task should be run. During local development, I would expect that my linked in modules do not get overwritten. 

Thoughts @brianleroux?

**Comment by brianleroux** [comment]
Tricky question. We def tried very hard to get link working w npm and it just created tonnes of issues. Sorta gave up on it. Could the shared folder work?

**Comment by brianleroux** [comment]
lets move this discussion to the official repos!
